<?php

/**
 * Véhicules du marché marocain — Marques & Modèles
 * Couvre : Voitures, Motos, Autocars / Minibus
 */
return [

    // ─── VOITURES ────────────────────────────────────────────────────────────
    'Dacia' => ['type' => 'voiture', 'modeles' => ['Logan', 'Sandero', 'Sandero Stepway', 'Duster', 'Jogger', 'Spring', 'Dokker', 'Lodgy', 'Bigster']],
    'Renault' => ['type' => 'voiture', 'modeles' => ['Clio', 'Clio 5', 'Megane', 'Megane E-Tech', 'Captur', 'Kadjar', 'Koleos', 'Austral', 'Arkana', 'Zoe', 'Scenic', 'Laguna', 'Fluence', 'Symbol', 'Trafic', 'Master', 'Express']],
    'Peugeot' => ['type' => 'voiture', 'modeles' => ['208', '308', '408', '508', '2008', '3008', '5008', 'Partner', 'Expert', 'Boxer', 'Rifter', 'Landtrek']],
    'Citroën' => ['type' => 'voiture', 'modeles' => ['C3', 'C3 Aircross', 'C4', 'C5 Aircross', 'C5 X', 'Berlingo', 'SpaceTourer', 'Jumpy', 'Jumper']],
    'Volkswagen' => ['type' => 'voiture', 'modeles' => ['Polo', 'Golf', 'Passat', 'Tiguan', 'T-Cross', 'T-Roc', 'Touareg', 'Taigo', 'ID.4', 'Caddy', 'Transporter', 'Crafter']],
    'Toyota' => ['type' => 'voiture', 'modeles' => ['Yaris', 'Corolla', 'Camry', 'C-HR', 'RAV4', 'Land Cruiser', 'Land Cruiser Prado', 'Hilux', 'Fortuner', 'Rush', 'Avanza', 'Hiace', 'Proace']],
    'Hyundai' => ['type' => 'voiture', 'modeles' => ['i10', 'i20', 'i30', 'Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Kona', 'Ioniq 5', 'Ioniq 6', 'H-1', 'H350', 'Staria']],
    'Kia' => ['type' => 'voiture', 'modeles' => ['Picanto', 'Rio', 'Cerato', 'Stinger', 'Sportage', 'Sorento', 'Telluride', 'Stonic', 'Niro', 'EV6', 'Carnival']],
    'Ford' => ['type' => 'voiture', 'modeles' => ['Fiesta', 'Focus', 'Mondeo', 'Puma', 'Kuga', 'Edge', 'Explorer', 'Mustang', 'Ranger', 'Transit', 'Transit Custom', 'Transit Connect']],
    'Fiat' => ['type' => 'voiture', 'modeles' => ['Panda', 'Tipo', '500', '500X', 'Doblo', 'Scudo', 'Ducato', 'Fiorino']],
    'Opel' => ['type' => 'voiture', 'modeles' => ['Corsa', 'Astra', 'Insignia', 'Mokka', 'Crossland', 'Grandland', 'Combo', 'Vivaro', 'Movano']],
    'Seat' => ['type' => 'voiture', 'modeles' => ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Alhambra']],
    'Skoda' => ['type' => 'voiture', 'modeles' => ['Fabia', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq']],
    'BMW' => ['type' => 'voiture', 'modeles' => ['Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'Série 6', 'Série 7', 'Série 8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'iX', 'iX3', 'i4', 'i5']],
    'Mercedes-Benz' => ['type' => 'voiture', 'modeles' => ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'Classe S', 'CLA', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'EQA', 'EQC', 'EQE', 'EQS', 'Vito', 'Classe V', 'Sprinter']],
    'Audi' => ['type' => 'voiture', 'modeles' => ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'e-tron GT', 'TT']],
    'Nissan' => ['type' => 'voiture', 'modeles' => ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Navara', 'Patrol', 'Pathfinder', 'Leaf', 'Ariya', 'NV200', 'NV300', 'Interstar']],
    'Suzuki' => ['type' => 'voiture', 'modeles' => ['Alto', 'Celerio', 'Swift', 'Baleno', 'Vitara', 'S-Cross', 'Jimny', 'Ignis', 'Carry']],
    'Mitsubishi' => ['type' => 'voiture', 'modeles' => ['Space Star', 'Colt', 'ASX', 'Eclipse Cross', 'Outlander', 'Pajero', 'L200', 'Express']],
    'Honda' => ['type' => 'voiture', 'modeles' => ['Jazz', 'Civic', 'Accord', 'HR-V', 'CR-V', 'ZR-V', 'Pilot', 'e:Ny1']],
    'Mazda' => ['type' => 'voiture', 'modeles' => ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-80', 'MX-30']],
    'Chevrolet' => ['type' => 'voiture', 'modeles' => ['Spark', 'Aveo', 'Cruze', 'Malibu', 'Trax', 'Trailblazer', 'Traverse', 'Captiva', 'Colorado', 'N300']],
    'Jeep' => ['type' => 'voiture', 'modeles' => ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator', 'Avenger']],
    'Land Rover' => ['type' => 'voiture', 'modeles' => ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar']],
    'Volvo' => ['type' => 'voiture', 'modeles' => ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40 Recharge', 'EX30', 'EX90']],
    'BAIC' => ['type' => 'voiture', 'modeles' => ['X35', 'X55', 'X75', 'BJ40', 'BJ60', 'EU5', 'X25', 'Rui', 'Senova']],
    'Chery' => ['type' => 'voiture', 'modeles' => ['Tiggo 4', 'Tiggo 4 Pro', 'Tiggo 7', 'Tiggo 7 Pro', 'Tiggo 8', 'Tiggo 8 Pro', 'Omoda 5', 'Arrizo 6', 'Arrizo 8']],
    'Geely' => ['type' => 'voiture', 'modeles' => ['Emgrand', 'Coolray', 'Okavango', 'Atlas', 'Atlas Pro', 'Tugella', 'Azkarra', 'Monjaro']],
    'MG' => ['type' => 'voiture', 'modeles' => ['MG3', 'MG5', 'MG6', 'MG HS', 'MG ZS', 'MG ZS EV', 'MG4', 'MG One', 'RX5', 'RX8']],
    'JAC' => ['type' => 'voiture', 'modeles' => ['J7', 'S3', 'S4', 'S5', 'T6', 'T8', 'iEV7', 'E-JS4']],
    'BYD' => ['type' => 'voiture', 'modeles' => ['Atto 3', 'Seal', 'Han', 'Tang', 'Dolphin', 'Seagull', 'Song Plus', 'Yuan Plus']],
    'Haval' => ['type' => 'voiture', 'modeles' => ['H6', 'H6 HEV', 'Jolion', 'Jolion HEV', 'H9', 'Dargo', 'Poer']],
    'Changan' => ['type' => 'voiture', 'modeles' => ['CS35 Plus', 'CS55 Plus', 'CS75 Plus', 'CS85', 'Alsvin', 'Uni-K', 'Hunter']],
    'Alfa Romeo' => ['type' => 'voiture', 'modeles' => ['Giulia', 'Stelvio', 'Tonale', 'Giulietta', '159']],
    'Porsche' => ['type' => 'voiture', 'modeles' => ['Cayenne', 'Macan', 'Panamera', '911', 'Taycan', 'Boxster', 'Cayman']],
    'Lexus' => ['type' => 'voiture', 'modeles' => ['IS', 'ES', 'GS', 'LS', 'NX', 'RX', 'GX', 'LX', 'UX', 'RZ']],
    'Infiniti' => ['type' => 'voiture', 'modeles' => ['Q30', 'Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX80']],
    'Subaru' => ['type' => 'voiture', 'modeles' => ['Impreza', 'Legacy', 'Forester', 'Outback', 'XV', 'Crosstrek', 'WRX', 'BRZ', 'Solterra']],
    'Isuzu' => ['type' => 'voiture', 'modeles' => ['D-Max', 'MU-X', 'Trooper']],
    'Ssangyong' => ['type' => 'voiture', 'modeles' => ['Tivoli', 'Korando', 'Rexton', 'Musso', 'Actyon']],

    // ─── MOTOS ───────────────────────────────────────────────────────────────
    'Yamaha (Moto)' => ['type' => 'moto', 'modeles' => ['YBR 125', 'FZ 150', 'FZ 250', 'MT-03', 'MT-07', 'MT-09', 'R15', 'R3', 'R6', 'R1', 'NMAX 125', 'NMAX 155', 'Aerox 155', 'XMAX 300', 'Tracer 700', 'Tracer 900', 'Tenere 700', 'TMAX 560']],
    'Honda (Moto)' => ['type' => 'moto', 'modeles' => ['CB 125', 'CB 150', 'CB 300', 'CB 500', 'CB 650', 'CB 1000', 'CBR 150', 'CBR 300', 'CBR 500', 'CBR 600', 'CBR 1000', 'PCX 125', 'PCX 160', 'Forza 300', 'Forza 350', 'X-ADV', 'Africa Twin', 'CRF 300']],
    'Kawasaki (Moto)' => ['type' => 'moto', 'modeles' => ['Z125', 'Z300', 'Z400', 'Z650', 'Z900', 'Z1000', 'Ninja 300', 'Ninja 400', 'Ninja 650', 'Ninja 1000', 'Versys 300', 'Versys 650', 'Versys 1000', 'KLX 150', 'KLX 300']],
    'Suzuki (Moto)' => ['type' => 'moto', 'modeles' => ['GSX 125', 'GSX 150', 'GSX-S 300', 'GSX-S 750', 'GSX-S 1000', 'V-Strom 650', 'V-Strom 1050', 'Burgman 200', 'Burgman 400', 'Address 125']],
    'Sym' => ['type' => 'moto', 'modeles' => ['Orbit 50', 'Orbit 125', 'Jet 14', 'Joymax 300', 'Cruisym 300', 'Maxsym 400', 'Wolf 150', 'GTS 125']],
    'Kymco' => ['type' => 'moto', 'modeles' => ['Agility 50', 'Agility 125', 'Like 125', 'People 125', 'People GTi 300', 'Super 8 150', 'X-Town 300', 'Xciting 400', 'CV3']],
    'Benelli' => ['type' => 'moto', 'modeles' => ['TNT 125', 'TNT 135', 'TNT 150', 'TNT 249', 'TNT 300', 'TRK 251', 'TRK 502', 'Leoncino 250', 'Leoncino 500', '502C']],
    'Lifan' => ['type' => 'moto', 'modeles' => ['LF 50', 'LF 100', 'LF 125', 'LF 150', 'LF 200', 'KPR 150', 'KPR 200', 'KPS 150']],
    'Loncin' => ['type' => 'moto', 'modeles' => ['LX 50', 'LX 125', 'LX 150', 'LX 200', 'GP 150', 'GP 250', 'Voge 300', 'Voge 500']],
    'Jincheng' => ['type' => 'moto', 'modeles' => ['JC 50', 'JC 100', 'JC 125', 'JC 150', 'AX 100']],
    'Daelim' => ['type' => 'moto', 'modeles' => ['S3 125', 'S3 250', 'VJF 125', 'VT 125', 'Roadwin 250']],
    'Piaggio' => ['type' => 'moto', 'modeles' => ['Liberty 50', 'Liberty 125', 'Liberty 150', 'Vespa GTS 125', 'Vespa GTS 300', 'Vespa Sprint', 'Medley 125', 'MP3 300', 'MP3 500']],
    'Aprilia' => ['type' => 'moto', 'modeles' => ['SR 125', 'SR 150', 'RS 125', 'RS 660', 'Tuono 660', 'SX 125', 'RX 125']],
    'KTM' => ['type' => 'moto', 'modeles' => ['Duke 125', 'Duke 200', 'Duke 250', 'Duke 390', 'Duke 690', 'Duke 890', 'RC 125', 'RC 200', 'RC 390', '790 Adventure', '890 Adventure', '1290 Super Adventure']],

    // ─── AUTOCARS / MINIBUS ───────────────────────────────────────────────────
    'Mercedes-Benz (Autocar)' => ['type' => 'autocar', 'modeles' => ['Sprinter 311 CDI', 'Sprinter 313 CDI', 'Sprinter 316 CDI', 'Sprinter 319 CDI', 'Sprinter 411 CDI', 'Sprinter 413 CDI', 'Sprinter 519 CDI', 'Travego', 'Tourismo', 'Intouro', 'Conecto']],
    'Iveco (Autocar)' => ['type' => 'autocar', 'modeles' => ['Daily 35S Minibus', 'Daily 50C Minibus', 'Daily 65C Minibus', 'Crossway', 'Evadys', 'Magelys']],
    'Isuzu (Autocar)' => ['type' => 'autocar', 'modeles' => ['Novo', 'NovoCiti', 'Turquoise', 'Citibus', 'A129', 'Novo Ultra']],
    'Yutong' => ['type' => 'autocar', 'modeles' => ['ZK6119', 'ZK6122', 'ZK6126', 'ZK6138', 'ZK6148', 'ZK6608', 'ZK6109', 'E12', 'ZK6816', 'ZK6930']],
    'King Long' => ['type' => 'autocar', 'modeles' => ['XMQ6117', 'XMQ6129', 'XMQ6900', 'XMQ6127', 'XMQ6125', 'XMQ6130', 'XMQ6800']],
    'Hino' => ['type' => 'autocar', 'modeles' => ['FC Minibus', 'FB Minibus', 'RK Bus', 'RM Bus', 'RN Bus', 'Poncho']],
    'Scania (Autocar)' => ['type' => 'autocar', 'modeles' => ['Touring', 'Interlink', 'OmniExpress', 'Citywide', 'Omnilink', 'Irizar i6']],
    'MAN (Autocar)' => ['type' => 'autocar', 'modeles' => ["Lion's Coach", "Lion's Intercity", "Lion's City", "Lion's Regio", 'ND202', 'ND262']],
    'Volvo Buses' => ['type' => 'autocar', 'modeles' => ['9700', '9900', '8900', 'B8R', 'B11R', 'B13R', 'B8L', '7900 Hybrid']],
    'Neoplan' => ['type' => 'autocar', 'modeles' => ['Cityliner', 'Tourliner', 'Skyliner', 'Starliner', 'Transliner']],
    'Temsa' => ['type' => 'autocar', 'modeles' => ['Safari', 'Diamond', 'Opalio', 'MD9', 'TS 35', 'Avenue']],
    'Fuso' => ['type' => 'autocar', 'modeles' => ['Rosa 24 places', 'Rosa 29 places', 'Canter Bus', 'Aero Bus']],
    'Toyota (Minibus)' => ['type' => 'autocar', 'modeles' => ['HiAce Minibus 12 places', 'HiAce Minibus 14 places', 'Coaster 30 places', 'Coaster 23 places']],
    'Hyundai (Minibus)' => ['type' => 'autocar', 'modeles' => ['County', 'Universe', 'H350 Minibus 17 places', 'H1 Minibus 12 places']],
    'Volkswagen (Minibus)' => ['type' => 'autocar', 'modeles' => ['Crafter 17 places', 'Crafter 20 places', 'Transporter 9 places']],
    'Ford (Minibus)' => ['type' => 'autocar', 'modeles' => ['Transit Minibus 9 places', 'Transit Minibus 12 places', 'Transit Minibus 15 places', 'Transit Minibus 17 places']],
    'Renault (Minibus)' => ['type' => 'autocar', 'modeles' => ['Master Minibus 9 places', 'Master Minibus 15 places', 'Master Minibus 17 places', 'Trafic Minibus 9 places']],

];
